### ISSUE TITLE
Error in Contao 4.13

### ISSUE THREAD

**Issue by johannes-bittner** [1up-lab/contao-language-dependent-modules-bundle#6]
After install, the Install-Tool fails with the error message: "Attempted to call an undefined method named "fetchAll" of class "Doctrine\DBAL\Statement"."

**Log:**
`
Uncaught Error: Call to undefined method Doctrine\DBAL\Statement::fetchAll()
{
    "exception": {}
}`

`Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\UndefinedMethodError: "Attempted to call an undefined method named "fetchAll" of class "Doctrine\DBAL\Statement"." at /vendor/oneup/contao-language-dependent-modules-bundle/src/Provider/ModuleProvider.php line 41
{
    "exception": {}
}`

**Stack Trace:** 
`Symfony\Component\ErrorHandler\Error\UndefinedMethodError:
Attempted to call an undefined method named "fetchAll" of class "Doctrine\DBAL\Statement".
  at vendor/oneup/contao-language-dependent-modules-bundle/src/Provider/ModuleProvider.php:41
  at Oneup\Contao\LanguageDependentModulesBundle\Provider\ModuleProvider->getModules(array())
     (vendor/oneup/contao-language-dependent-modules-bundle/src/EventListener/LoadDataContainerListener.php:91)
  at Oneup\Contao\LanguageDependentModulesBundle\EventListener\LoadDataContainerListener->onLoadDataContainer('tl_module')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaLoader.php:119)
  at Contao\DcaLoader->loadDcaFiles(false)
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaLoader.php:68)
  at Contao\DcaLoader->load(false)
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:1427)
  at Contao\Controller::loadDataContainer('tl_module')
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:386)
  at Contao\Backend->getBackendModule('themes', null)
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:168)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:49)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:152)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/index.php:44)`

Same error message when accessing the backend after installation.

**Comment by bytehead** [comment]
In Contao 4.13 you don't need that extension anymore - it's built-in! 😎 `Root page dependent modules`

But the problem here is Doctrine in version 3.x. May I have to add a conflict.

**Comment by johannes-bittner** [comment]
🙈  ... you're right ...

**Comment by bytehead** [comment]
I've published version `1.1.1` which contains a conflict with `doctrine/dbal` >= 3.0.
